// This file was generated by Prisma, and assumes you have installed the following:
// npm install --save-dev prisma dotenv
import "dotenv/config";
import { defineConfig } from "prisma/config";

export default defineConfig({
  schema: "prisma/schema.prisma",
  migrations: {
    path: "prisma/migrations",
  },
  datasource: { 
    url: process.env["DATABASE_URL"]!,
  },
});

// ======================= List of problems met =====================
// 1)
//  url: process.env["DATABASE_URL"]!, the ! was made bcz process.env.DATABASE_URL might not exist
// so its type is string | undefined && exactOptionalPropertyTypes: true in tsconfig so ! reassures that non null
// 2)
// prisma uses imports and exports that aren't communjs so the type we swtiched to is module but import export became obligatoru

